name: Build and Push Base Image

on:
  push:
    branches: [main]
    paths: [Dockerfile.base]
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/shopify/lighthouse-ci-action
  IMAGE_TAG: "3.0.0"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build base image
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -f Dockerfile.base .

      - name: Push base image
        run: docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
